### ISSUE TITLE
Memory bloat when repository has big .gitignore/.gitattributes (thousands of entries)

### ISSUE THREAD

**Issue by Sebazzz** [git-as-svn/git-as-svn#306] opened 2019-11-04 21:33 UTC
Mentioned in [issue #66](https://github.com/bozaro/git-as-svn/issues/66#issuecomment-549537135):

Every revision seems to get a little bit slower (as if there is some kind of O(n²) problem here). I've tried it with `-Xmx4g` and a repo with 28000 commits - I believe the repository comparable to [dotnet/coreclr](https://github.com/dotnet/coreclr/). The checked out full repository size just below 1GB to give an idea of the size.

The startup process is slow for such repository, and every revision that is processed (9538 in my case) seems to be processed a little bit slower. Eventually you get almost 100% CPU usage (VM with 4 available virtual processors). This was around revision 5500 of 9538. I attempted to restart the process, after restarting it started over.

I took a short look at the code, and the computed information [seems to be cached](https://github.com/bozaro/git-as-svn/blob/b2c75c5ab764fe962b0e51df8c3172dae5951530/src/main/java/svnserver/repository/git/GitBranch.java#L338) but I don't think the cached is flushed so if the startup process is interrupted (or would crash) the revisions processed so far are gone.

Running on:
- Windows Server 2016
- 4x cpu core
- 16GB internal memory
- jdk1.8.0_202

Thread dump of current process (revision 2331 of 9538): [git-as-svn-threaddump-rev-2331of9538.txt](https://github.com/bozaro/git-as-svn/files/3806158/git-as-svn-threaddump-rev-2331of9538.txt). I took a couple of thread dumps and every time the stack up from and including `collectRename` appears to be same.

I will let it run the night (it is 22:33 here) and see in the morning how far it went.

**Comment by slonopotamus** [comment] 2019-11-04 21:48
1. Try setting `renameDetection` to `false` in git-as-svn config. This is not going to be a final solution, of course.
2. You're correct, `revisions` list is kept in memory, though it is rather cheap. All heavy stuff is either read from git repo (like, file blobs) or if it is expensive to compute (like, md5 of blobs) is stored in MapDB file.
3. You could attach JConsole to git-as-svn process to quickly confirm that there are issues with memory consumption
4. Do you observe degrading indexing speed on [dotnet/coreclr](https://github.com/dotnet/coreclr/) so it can be used as a repro?

**Comment by Sebazzz** [comment] 2019-11-05 05:53
1. That's fine for me. I don't care about renames. The only thing I care about is that when something has changed in git, it reports in svn as changed as well. The underlying reason is that I use git-as-svn as a shim for a system that has no git support built-in (we came from svn). I actually don't even need the full history, just the *x* number of revisions.

4. I will come back to you on that.

New thread dump, now almost 99% CPU consumption at rev 6561. No noticable difference in the stack dump for me at least:
[git-as-svn-threaddump-rev-6561of9538.txt](https://github.com/bozaro/git-as-svn/files/3807395/git-as-svn-threaddump-rev-6561of9538.txt)

**Comment by slonopotamus** [comment] 2019-11-05 08:28
Okaaay. I ran some tests against `dotnet/coreclr` repo on i7-6700 (Linux, openjdk 1.8.0_222):

1. With rename detection disabled, its 13k revisions is indexed at ~900 revs/sec.
2. With rename detection enabled, indexing starts  at around 30 revs/sec, then slowly drops to 15rev/s around 5k of revisions and finishes at 13 revs/sec.

Uhh... What I can say... Rename detection is slow as hell. I'm not sure how to fix it yet. We're fully relying on JGit for that. I rechecked [GitBranch.collectRename](https://github.com/bozaro/git-as-svn/blob/master/src/main/java/svnserver/repository/git/GitBranch.java#L374) code and think we're using JGit the proper way. Compare with [BlameGenerator.findRename](https://github.com/eclipse/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/blame/BlameGenerator.java#L1023) from JGit, for example.

If we do not find a way to make rename detection noticeably faster, perhaps it should be disabled by default and a Big Fat Warning about rename performance hit put in docs.

**Comment by Sebazzz** [comment] 2019-11-05 10:10
What was the memory usage? Even with Xmx6g I'm getting OutOfMemoryExceptions, with my local repo. This is with rename detection disabled.

**Comment by slonopotamus** [comment] 2019-11-05 10:45
`-Xmx512m`

**Comment by slonopotamus** [comment] 2019-11-05 10:46
Reopening issue for now since you say that even with disabled rename detection you have high memory usage.

**Comment by Sebazzz** [comment] 2019-11-05 11:27
I almost got to the last 1000 revisions, but a crash happened due to GC overhead limit exceeded. This with Xmx8g. 

[git-as-svn-gc-crash.txt](https://github.com/bozaro/git-as-svn/files/3808721/git-as-svn-gc-crash.txt)

**Comment by slonopotamus** [comment] 2019-11-05 12:57
I also tried git-as-svn 1.21.8 on Windows. Same, `dotnet/coreclr` easily fits within `-Xmx512m`.

So, I see two ways from here:
1. You take heap dump and/or memory profile using your repo and share it. For example, `-XX:+HeapDumpOnOutOfMemoryError` JVM option will create a `.hprof` file that can be used to analyze what data uses JVM heap memory.
2. You find a public repo (or create an artificial one) that I can use to reproduce the problem

Bonus thoughts:
1. You never specified what git-as-svn version you use
2. Are you _sure_ that you increased heap size? Default `-Xmx512m` can be not enough for big repos, though `-Xmx8g` is supposed to handle a multi-dozen-gigabyte ones with hundreds of thousands of files.

**Comment by slonopotamus** [comment] 2019-11-05 13:00
> Second time succeeded, but failed on the second repository due to the memory being full.

When you have _multiple_ huge repos within the same git-as-svn instance, you may want to set `parallelIndexing: false`, this reduces peak memory usage during startup.

**Comment by Sebazzz** [comment] 2019-11-05 13:03
> You never specified what git-as-svn version you use

True 👍 The latest from the release tab (1.21.8).

> Are you sure that you increased heap size? Default -Xmx512m can be not enough for big repos, though -Xmx8g is supposed to handle a multi-dozen-gigabyte ones with hundreds of thousands of files.

Yes it runs with 8GB memory usage in Task Manager now, else it fails earlier. The command line also shows the Xmx switch present.

**Comment by slonopotamus** [comment] 2019-11-05 19:13
800MB of `EqualsMatcher`??? What the hell is going on...

Do you have something funny in your `gitattributes`? Dunno, 1 million of entries or something like that :) How many files are there in repo? 10k-100k-1M-10M? How many files change per commit (roughly, I don't need exact number)?

**Comment by slonopotamus** [comment] 2019-11-05 19:15
Also: what is your indexing speed (revs/s)?

**Comment by Sebazzz** [comment] 2019-11-05 19:40
Around 3000 (repo 1) and 1500 (repo 2) rules apparently. A typical subgit conversion result I guess. The repository itself has about 30000 files. Generally not much files change per revision, but it is an old project with long running (~5 months) feature branches which are merged eventually. The repository is now git, but was svn, and cvs before that. Never mind it was on a svn server without mergeinfo capability in de early days (because that didn't exist yet).

Indexing speed is around 171, then drops to 50, then from 30 slowly to almost 0 as the memory fills up. (Now trying on GraalVM)

**Comment by slonopotamus** [comment] 2019-11-05 19:48
> Now trying on GraalVM
No, wait, that won't fix anything. 1500-3000k of `.gitattributes` rules is far from normal, we didn't test such cases. Our `.gitattributes` is hand-crafted and are < 100 entries.

While I'm looking into where we lose so much memory due to `.gitattributes`, what size is `.gitignore`?

**Comment by Sebazzz** [comment] 2019-11-05 19:55
Oh sorry, I made a mistake, I meant the `.gitignore` is 3000 and 1500. 

`.gitattributes` is around 10000 for repo 1 and 7000 for repo 2. subgit indeed went crazy.

**Comment by slonopotamus** [comment] 2019-11-05 20:05
Holy goodness. Now we know the cause of your problem. Thanks for the VisualVM screenshot, it was the key to this puzzle.

Until `.gitattributes`/`.gitignore` handling code is fixed, the only workarounds are:

a. Further increase heap memory
b. Rewrite your history (creating new commit won't help) to transform `.gitattributes`/`.gitignore` to something more adequate.

**Comment by Sebazzz** [comment] 2019-11-05 20:09
Since we're still in de pre-stages of migrating to git, I think I will transform the repositories again and add directives for subgit to prevent adding .gitignore and .gitattribute files for these two repositories.  Still, I will let you know how it goes :)

**Comment by slonopotamus** [comment] 2019-11-05 20:16
P.S. If you missed it, I released 1.21.9 today with much faster rename detection. It is still a bit slower than no rename detection, but now fast enough (x50 to what it was) to be actually usable on large scale.

**Comment by Sebazzz** [comment] 2019-11-05 20:17
What is the difference with and without rename detection? Then it just shows a file as added or removed instead of moved in SVN?

**Comment by slonopotamus** [comment] 2019-11-05 20:20
Yeah, rename detection adds `svn:copy-from` metadata, so svn tools understand where file originated from.

**Comment by Sebazzz** [comment] 2019-11-06 09:39
> Still, I will let you know how it goes :)

Works fine now, initial import takes a bit longer but then it works fine. I'm running into hook issues on Windows, will open a separate issue for that.

**Closed** 2022-05-31 11:41 UTC
Labels: bug
